services:
  sgcc_electricity_app:
    image: ghcr.io/poiig/ha_sgcc_electricity:latest
    # 如果已配置 Docker Hub，可改为: <dockerhub_user>/ha_sgcc_electricity:latest
    container_name: sgcc_electricity
    env_file:
      - .env
    network_mode: "host"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - PYTHON_IN_DOCKER=PYTHON_IN_DOCKER
    restart: unless-stopped
    volumes:
      - ./data:/data
    init: true
